version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"


  app:
    image: web-container
    build:
      context: .
      dockerfile: src/Dockerfile

    command: sh -c "/app/src/entrypoint.sh"
    volumes:
      - .:/src
    depends_on:
      - db
    env_file:
      - /src/.env

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: