# Generated by Django 4.2.9 on 2024-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='handle',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='handle',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handle',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
