# Generated by Django 4.2.9 on 2024-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='handle',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
