# Generated by Django 4.2.9 on 2024-02-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_table_handle_alter_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='menu_item',
        ),
    ]
