# Generated by Django 4.2.9 on 2024-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_section_table_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='handle',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
