# Generated by Django 4.2.10 on 2024-02-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_menucategory_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
