# Generated by Django 4.2.9 on 2024-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_order_options_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
