# Generated by Django 4.2.10 on 2024-03-08 11:49

from django.db import migrations, models
import shop.models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.category_image_upload_path, validators=[shop.validators.validate_file_extension, shop.validators.validate_file_size, shop.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path, validators=[shop.validators.validate_file_extension, shop.validators.validate_file_size, shop.validators.validate_image]),
        ),
    ]
