name: Build and Push to DigitalOcean Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DigitalOcean Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRY_USERNAME }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: src/Dockerfile
        push: true
        tags: registry.digitalocean.com/orderly-registry/orderly-image:latest